### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by Levi-Lesches** [fgsoruco/opencv_4#10]
Hello @fgsoruco, I'm working on a project that needs OpenCV on Windows and Linux. I used Python's `cv2` library last year, but this year I wanted to switch to Dart. I noticed that this package is mobile-only, so over the past few days I've created desktop support using `dart:ffi` and would like to discuss integrating it into your package so as not to clutter pub.dev with multiple packages.

Here's my process: 
- Dart's ffi only supports C, not C++
- OpenCV is entirely C++. There is a legacy C API, but the code within has been replaced with print statements warning not to use it
- I wrote a C "wrapper" layer around the functions I wanted to call -- eg, `VideoCapture.read()`, `imshow`, etc -- that calls the C++ code
- Compiled the C wrapper using WSL (`.so`) and Windows (`.dll`) and ran `ffigen` on the wrapper's header file
- Load the `.so` or `.dll` wrapper into `dart:ffi` and write a wrapper class to do what I want

Here's how that turns out: 
<details><summary><code>wrapper.h</code></summary>
<br>

```c
// wrapper.h
#include <stdint.h>

/// Mock the VideoCapture class by using a fake struct.
/// 
/// This works because the actual implementation is in C++ with the proper class. This struct
/// workaround is just so C-based code can read and understand [VideoCapture] in this file.
struct VideoCapture;
typedef struct VideoCapture VideoCapture;

struct Mat;
typedef struct Mat Mat;

// Implement all Object-Oriented code in functional style.
#ifdef __cplusplus
extern "C" {
#endif
  // VideoCapture code
  VideoCapture* VideoCapture_getByIndex(int index);
  void VideoCapture_destroy(VideoCapture* capture);
  void VideoCapture_release(VideoCapture* capture);
  int VideoCapture_isOpened(VideoCapture* capture);
  int VideoCapture_read(VideoCapture* capture, Mat* image);

  // Matrix code
  Mat* Mat_create();
  void Mat_destroy(Mat* matrix);

  // Misc code
  void imshow(Mat* image);
  int encodeJpg(Mat* image, int quality, uint8_t* buffer);
  void setLogLevel(int level);
#ifdef __cplusplus
}
#endif
```
</details>

<details><summary><code>camera.dart</code></summary>
<br> 

```dart
// camera.dart
import "dart:io";
import "dart:typed_data";
import "dart:ffi" as ffi;
import "package:ffi/ffi.dart";

import "generated_bindings.dart";  // using package:ffigen

const path = r"opencv\wrappers\winbuild\Debug\wrapper.dll";

class Camera {
  final OpenCV native;  // generated using package:ffigen based on wrapper.h
  final int index;
  final arena = Arena();
  late final ffi.Pointer<VideoCapture> camera;
  late final ffi.Pointer<Mat> image;

  Camera(this.index) :
    native = OpenCV(ffi.DynamicLibrary.open(path))
  {
    native.setLogLevel(0);  // 0 = silent
    camera = native.VideoCapture_getByIndex(index);
    image = native.Mat_create();
  }

  void dispose() {
    native.VideoCapture_release(camera);
    native.VideoCapture_destroy(camera);
    native.Mat_destroy(image);
    print("Camera disposed!");
  }

  bool get isOpened => native.VideoCapture_isOpened(camera) != 0;

  bool read() => native.VideoCapture_read(camera, image) != 0;

  void display() => native.imshow(image);

  Future<bool> saveScreenshot(File file, {int quality = 75}) async {
    read();
    final buffer = arena<ffi.Uint8>(50000);
    final size = native.encodeJpg(image, quality, buffer);
    if (size == 0) return false;
    final Uint8List data = ffi.Uint8Pointer(buffer).asTypedList(size);
    file.writeAsBytes(data, flush: true);
    return true;
  }
}
```
</details>

<details><summary><code>main.dart</code></summary>
<br> 

```dart
// main.dart
import "dart:io";
import "package:dart/cv2.dart";

Future<void> main2(Camera camera) async {
  print("Camera is: ${camera.isOpened ? 'Connected' : 'Not connected'}");
  while (true) {
    final success = camera.read();
    if (!success) { print("Something went wrong!"); break; }
    camera.display();
    Future<void>.delayed(Duration(milliseconds: (1000/60).round()));
  }
}

void main() async {
  final camera = Camera(0);
  try { await main2(camera); }
  finally { camera.dispose(); }
}
```
</details>

This would be a bit more than a PR since you'd need to integrate the C/C++/OpenCV side of things, but I'm happy to help walk you through it. Or, if this is too far out of scope for your package, I can make my own. What do you think?

**Comment by anderson-** [comment]
@Levi-Lesches I'll be happy to help you If you need, I don't have much experience with opencv (I used in python before), but I'll need a package for desktop (linux/macOS) too.

**Comment by Levi-Lesches** [comment]
Thanks for the offer. I opened https://github.com/flutter/flutter/issues/128495 and got feedback from the Flutter team: 

> The goal of the camera plugin is to provide Flutter developers access to the system-provided camera APIs (e.g., AVFoundation, MediaRecorder, Media Foundation), so building on top of (and distributing) a third-party library is out of scope. If you're interested in making it generally available, creating a new plugin would be the path forward. You have a couple of options there:
> - You could make a completely new stand-alone plugin that people could use instead of camera.
> - You could create unendorsed federated implementations of camera using camera_platform_interface, such that people could use camera but with your underlying implementation.

So I'm working on that now. I'm working under the name `package:opencv_camera`, which you'll be able to use in the same way you can currently use the `package:camera` plugin. No GitHub repo yet though.
